# Generated by Django 5.2.7 on 2025-12-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_answer_author_alter_answer_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(auto_created=True, default='', max_length=25, verbose_name='Обображаемое имя'),
        ),
    ]
